name: Keep Alive

on:
  schedule:
    - cron: '0 */10 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        run: curl -s -o /dev/null https://bdem-hb.streamlit.app/
